---
- name: Reload Ollama daemon
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ ollama_service_name }}"
    state: restarted
  become: true
  listen: Reload Ollama daemon
  when: ollama_state == 'present'
